#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, find a compliant one and define the SHELL environment
#       variable to point to it. The minimal requirements are that 'echo' accepts
#       the -n option and that the 'test' utility is available.
#
#   Important for patching:
#
#   (2) This script is generated from the template file
#       base-services/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       in the Gradle distribution.
#
#   (3) The vast majority of modifications should be made to the template file
#       rather than this generated script. The template uses variable substitution
#       to fill in values from the start script configuration. It is copied to
#       this file during Gradle distribution generation.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25031)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo >&2 "$*"
}

die () {
    echo >&2 "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined: we rely on the fact that shells
        # like bash and zsh set up MAX_FD as the highest limit seen so far.
        # We can't check for unlimited with -z because its literal value may be
        # large but finite on some systems (e.g. Linux with 1M handles).
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit: $?. Using 1024."
        if [ $MAX_FD = "unlimited" ] ; then
            MAX_FD=maximum
        fi
        ;;
    esac
    case $MAX_FD in  #(
      0) warn "Cannot set maximum file descriptors to 0: will use 1024." ;;
      1) warn "Cannot set maximum file descriptors to 1: will use 1024." ;;
      2) warn "Cannot set maximum file descriptors: will use 1024." ;;
      maximum)
        # In POSIX sh, ulimit -n is undefined: we rely on the fact that shells
        # like bash and zsh set up ulimit -n as the highest limit seen so far.
        # We can't check for unlimited with -z because its literal value may be
        # large but finite on some systems (e.g. Linux with 1M handles).
        MAX_FD=$( ulimit -n ) ||
            warn "Could not query file descriptor limit: $?. Using 1024."
        if [ $MAX_FD = "unlimited" ] ; then
            MAX_FD=maximum
        fi
        ;;
      '') warn "Maximum file descriptor limit is not set: will use 1024." ;;
      *)
        # In POSIX sh, ulimit -n is undefined: we rely on the fact that shells
        # like bash and zsh set up ulimit -n as the highest limit seen so far.
        if ! ulimit -n "$MAX_FD" ; then
            warn "Could not set maximum file descriptors to $MAX_FD: $?."
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Save the main args in a variable to allow GC to collect the main args array.
MAIN_ARGS="$*"

exec "$JAVACMD" $MAIN_ARGS